### PR TITLE
Use correct filename address for syscall

### PR DESCRIPTION
**Pull request by baltazarortiz**
Currently, the /bin/sh string is written correctly, but then the wrong address is provided to the execve call.

Fixes issue #65

### CODE REVIEW

**Comment by sashs** [comment]
Hi,
thank you for the fix. Could you explain what exactly was wrong?

**Comment by sashs** [comment]
Unfortunately, the tests does not test ropper completely. I think your fix also contains address errors. 
At least for 32bit the old version should work. In order to fix the bug you mentioned it is enough to remove the 0x1000. That means in your code should be `nulladdress = section.offset + length`

**Comment by baltazarortiz** [comment]
No problem - the full writeup with an example chain is in issue #65, but the general problem is that the script was writing the string to one location, then using the null byte location later when it should have been using the string location. 

I only tested the fix for 64 bit - 32 bit appeared to have the same problem so I changed it, but it's very possible it already worked! I'll do some more testing soon and make sure I don't have address errors.

**Comment by sashs** [comment]
I saw the example chain, however, in this chain the cmdaddress != nulladdress (0x00000000002cc080 != 0x00000000002cc088). 
Between the cmd address and the nulladdress is a difference of 8 byte. 

However, indeed there is a bug. The command is written at the address 0x00000000002cb080 and the address that is used as the first argument is 0x00000000002cc080. This is because of the addition of 0x1000.

**Comment by sashs** [comment]
The ropchain for 32bit is correct, however, the 0x1000 should be removed as well, the command is written 0x1000 behind the start of the .data section.

**Comment by sashs** [comment]
In your code the problem is that you cannot be sure that at your nullbyte address are nullbytes. Those are also written by the ropchain. 
If you change that in your code, I will merge it.

**Comment by baltazarortiz** [comment]
Fixed and pushed - Works with the 64 bit binary now, apparently when I compile it as 32 bit it doesn't have a syscall/int 0x80 gadget, so once I'm working with more complicated binaries I can double check. 

For my example binary, I also had to implement the fix in #70 before I could generate correct chains, but this fix should be sufficient on its own if your binary doesn't have the multi pop gadgets.

**Comment by sashs** [comment]
merged. thx!

**Pull request merged**
