### PR TITLE
Add SPARC64 support

### PR DESCRIPTION
**Pull request by xairy**

### CODE REVIEW

**Comment by xairy** [comment]
Don't merge yet, found an issue with regexps, will fix and ping when done.

**Comment by xairy** [comment]
I don't see an easy way to fix it though. The issue is that with the current regexp-based byte-granular way of matching instructions we'll also match `addccc` with the regexp for `jmpl`. I don't think it's a big issue though, so this change is probably good enough as is.

**Comment by sashs** [comment]
Hi, 

first of all thank you. 
I haven't looked at Sparc yet. Why does the regexp match `addccc` and `jmpl`. Do those instruction have the same opcode?

**Comment by xairy** [comment]
No, `jmpl` has `0b10XXXXX1` as the first byte, while `addccc` has `0b10XXXXX0` (see the instruction reference [here](https://cr.yp.to/2005-590/sparcv9.pdf)). The issue is that when I do `[\x81-\xbf]` it also matches e.g. `0x82 == 0b10000010`, which is `addccc`. I don't see an easy way to describe `0b10XXXXX1` with a single regexp. Generating something like `[\x81\x83\x85...\xbf]` would work I guess.

**Comment by sashs** [comment]
Thx. Yes, that is what you have to do. When I remember correctly I did something similar for x86.

**Comment by xairy** [comment]
OK, should be fixed now, PTAL.

**Pull request merged**
